authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('predictions', views.PredictionView.as_view(), name='predictions'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
]

strengthpredictor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls'))
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

class WorkoutWeek(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    end_date = models.DateTimeField('date ended')
    total_calories = models.IntegerField(default=0)
    total_sleep = models.IntegerField(default=0)
    total_chest = models.IntegerField(default=0)
    total_shoulders = models.IntegerField(default=0)
    total_triceps = models.IntegerField(default=0)
    total_protein = models.IntegerField(default=0)
    total_carbs = models.IntegerField(default=0)
    bench_max = models.IntegerField(default=0)

    def __str__(self):
        return str(self.end_date)

    # admin pass is 1234

authentication/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.urls import reverse
import joblib
import numpy as np
import sklearn
from datetime import datetime, date, timedelta


from .models import WorkoutWeek

class IndexView(generic.ListView):
    template_name = 'authentication/index.html'
    context_object_name = 'workouts_list'

    def post(self, request):
        user = get_object_or_404(User, pk=int(request.POST.get('user')))
        end_date = request.POST.get('end_date')
        total_calories = request.POST.get('total_calories')
        total_sleep = request.POST.get('total_sleep')
        total_chest = request.POST.get('total_chest')
        total_shoulders = request.POST.get('total_shoulders')
        total_triceps = request.POST.get('total_triceps')
        total_protein = request.POST.get('total_protein')
        total_carbs = request.POST.get('total_carbs')
        bench_max = request.POST.get('bench_max')

        new_workout = WorkoutWeek.objects.create(
            user=user,
            end_date=end_date, 
            total_calories=total_calories, 
            total_sleep=total_sleep,
            total_chest=total_chest,
            total_shoulders=total_shoulders,
            total_triceps=total_triceps,
            total_protein=total_protein,
            total_carbs=total_carbs,
            bench_max=bench_max
        )

        new_workout.save()

        messages.success(request, 'Workout Added.')

        return redirect('authentication:index')

    def get_queryset(self):
        return WorkoutWeek.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['data'] = json.dumps(
            [
                {
                    'id': obj.id,
                    'end_date': obj.end_date.isoformat(),
                    'total_calories': obj.total_calories,
                    'total_sleep': obj.total_sleep,
                    'total_chest': obj.total_chest,
                    'total_shoulders': obj.total_shoulders,
                    'total_triceps': obj.total_triceps,
                    'total_protein': obj.total_protein,
                    'total_carbs': obj.total_carbs,
                    'bench_max': obj.bench_max,
                    'user': obj.user.id
                }
                for obj in WorkoutWeek.objects.all()
            ]
        )
        return context

class PredictionView(generic.ListView):
    template_name = 'authentication/predictions.html'
    context_object_name = 'workout_list'

    def get_queryset(self):
        return WorkoutWeek.objects.all()

    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=int(request.POST.get('user')))
        total_calories = int(request.POST.get('total_calories'))
        total_sleep = int(request.POST.get('total_sleep'))
        total_chest = int(request.POST.get('total_chest'))
        total_shoulders = int(request.POST.get('total_shoulders'))
        total_triceps = int(request.POST.get('total_triceps'))
        total_protein = int(request.POST.get('total_protein'))
        total_carbs = int(request.POST.get('total_carbs'))
        bench_max = int(WorkoutWeek.objects.latest('end_date').bench_max)
        predict_weeks = int(request.POST.get('predict_weeks'))

        temp = [
            {
                'id': obj.id,
                'end_date': obj.end_date.isoformat(),
                'total_calories': obj.total_calories,
                'total_sleep': obj.total_sleep,
                'total_chest': obj.total_chest,
                'total_shoulders': obj.total_shoulders,
                'total_triceps': obj.total_triceps,
                'total_protein': obj.total_protein,
                'total_carbs': obj.total_carbs,
                'bench_max': obj.bench_max,
                'user': obj.user.id
            }
            for obj in WorkoutWeek.objects.all()
        ]

        model_clone = joblib.load('authentication/my_model.pkl')
        temp_bench_max = bench_max

        predictions = []

        for i in range(1, int(predict_weeks)+1):
            input_data = (total_calories,total_sleep,total_chest,total_shoulders,total_triceps,
            total_protein,total_carbs,temp_bench_max)
            input_data_as_numpy_array = np.asarray(input_data)
            input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
            prediction = model_clone.predict(input_data_reshaped)
            if prediction[0]==1:
                temp_bench_max += 5
            temp.append({
                'id': 0,
                'end_date': (WorkoutWeek.objects.latest('end_date').end_date + timedelta(weeks=i)).isoformat(),
                'total_calories': total_calories,
                'total_sleep': total_sleep,
                'total_chest': total_chest,
                'total_shoulders': total_shoulders,
                'total_triceps': total_triceps,
                'total_protein': total_protein,
                'total_carbs': total_carbs,
                'bench_max': temp_bench_max,
                'user': user.id
            })

        data = json.dumps(temp)

        return render(request, 'authentication/predictions.html', {'data': data})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['data'] = json.dumps(
            [
                {
                    'id': obj.id,
                    'end_date': obj.end_date.isoformat(),
                    'total_calories': obj.total_calories,
                    'total_sleep': obj.total_sleep,
                    'total_chest': obj.total_chest,
                    'total_shoulders': obj.total_shoulders,
                    'total_triceps': obj.total_triceps,
                    'total_protein': obj.total_protein,
                    'total_carbs': obj.total_carbs,
                    'bench_max': obj.bench_max,
                    'user': obj.user.id
                }
                for obj in WorkoutWeek.objects.all()
            ]
        )
        return context


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirmpassword = request.POST.get('confirmpassword')

        if password != confirmpassword:
            print(password, confirmpassword)
            messages.error(request, 'Your username and/or password was not correct.')
            return redirect('signup')

        myuser = User.objects.create_user(username, email, password)
        myuser.first_name = firstname
        myuser.last_name = lastname

        myuser.save()

        messages.success(request, 'Your account has been successfully created.')

        return redirect('authentication:index')

    return render(request, "authentication/signup.html")

def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        print(username, password)
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('authentication:index')
        else:
            messages.error(request, 'Your username and/or password was not correct.')
            return redirect('authentication:index')

    return render(request, "authentication/signin.html")

def signout(request):
    logout(request)
    messages.success(request, 'Logged out succesfully!')
    return redirect('authentication:index')

authentication/templates/authentication/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'authentication/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'authentication/cover.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'authentication/dashboard.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>

<div style="display: none" id="jsonData" data-json="{{ data }}"></div>

<!-- Begin Modal Body -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div style="display: flex; flex-direction: column">
          <h5 class="modal-title text-dark" id="exampleModalLabel">Add an Entry</h5>
          <p class="text-dark">The values correspond to the 7 days before and including the date entered below</p>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'authentication:index' %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
            <div class="row">
              <input type="date" class="form-control" name="end_date" placeholder="Date">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_calories" placeholder="Total Calories">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_sleep" placeholder="Total Sleep (in minutes)">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_chest" placeholder="Total Amount of sets for chest done above 70% 1RM">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_shoulders" placeholder="Total Amount of sets for shoulders done above 70% 1RM">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_triceps" placeholder="Total Amount of sets for triceps done above 70% 1RM">
            </div>
              <div class="row">
                <input type="text" class="form-control" name="total_protein" placeholder="Total Amount of protein consumed (grams)">
              </div>
              <div class="row">
                <input type="text" class="form-control" name="total_carbs" placeholder="Total Amount of carbs consumed (grams)">
              </div>
              <div class="row">
                <input type="text" class="form-control" name="bench_max" placeholder="Bench Max (in lbs)">
              </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn bg-dark text-light">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

  <!-- End Modal Body -->
<body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
        <div>
            <nav class="nav nav-masthead justify-content-center float-md-start">
                <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
                {% if user.is_authenticated %}
                <a class="nav-link fw-bold py-1 px-0" href="#">Machine Learning Predictions</a>
                {% endif %}
            </nav>
            <div class="float-md-end">
                {% if user.is_authenticated %}
                <span class="mx-2 fw-bold text-light mx-1">{{ user.first_name }} {{ user.last_name }}</span>
                <a href="{% url 'authentication:signout' %}" class="btn btn-secondary fw-bold border-white bg-white">Sign Out</a>
                {% else %}
                <a href="{% url 'authentication:signin' %}" class="btn btn-secondary fw-bold border-white bg-dark text-light mx-1">Sign In</a>
                <a href="{% url 'authentication:signup' %}" class="btn btn-secondary fw-bold border-white bg-white">Sign Up</a>
                {% endif %}
            </div>
        </div>
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" style="text-shadow: none" role="alert">
            <strong>Success! </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        </header>
        
        {% if user.is_authenticated %}
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Bench Strength</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                    </div>
                    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                    <span data-feather="calendar" class="align-text-bottom"></span>
                    This week
                    </button>
                </div>
            </div>
    
            <canvas class="w-full" id="myChart" width="900" height="380"></canvas>

            <!-- 
                 - Total Calories Consumed that week
                - Total Amount of Sleep that week
                - Total Amount of sets for chest done above 70% 1RM
                - Total Amount of sets for shoulders done above 70% 1RM
                - Total Amount of sets for triceps done above 70% 1RM
                - Total Amount of protein consumed
                - Total Amount of carbohydrates consumed
             -->
            
             <!-- Begin modal button -->
             <button type="button" class="btn btn-secondary fw-bold border-white bg-white mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Add New Entry
            </button>
            <!-- End Modal button -->
            <footer class="mt-auto text-white-50">
                <p>Created by <a href="https://ianboldea.com/" class="text-white">Ian Boldea</a>, &copy; 2022</p>
            </footer>
            <!-- END GRAPH -->
        {% else %}
            <main class="px-3">
            <h1>Let's get you huge.</h1>
            <p class="lead">Use machine learning to get your chest yoked.</p>
            <p class="lead">
                <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
            </p>
            </main>

            <footer class="mt-auto text-white-50">
                <p>Created by <a href="https://ianboldea.com/" class="text-white">Ian Boldea</a>, &copy; 2022</p>
            </footer>
        {% endif %}
    </div>
    <script src="{% static 'authentication/feather.min.js' %}"></script>
    <script src="{% static 'authentication/Chart.min.js' %}"></script>
    <script src="{% static 'authentication/date_fns.min.js' %}"></script>
    <script src="{% static 'authentication/chartjs-adapter-date-fns.bundle.min.js' %}"></script>
    <script src="{% static 'authentication/dashboard.js' %}"></script>
</body>
    

authentication/templates/authentication/predictions.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'authentication/style.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'authentication/cover.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'authentication/dashboard.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>

<div style="display: none" id="jsonData" data-json="{{ data }}"></div>
<div style="display: none" id="userData" data-json="{{ user.id }}"></div>

<!-- Begin Modal Body -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div style="display: flex; flex-direction: column">
          <h5 class="modal-title text-dark" id="exampleModalLabel">Predict Future Values</h5>
          <p class="text-dark">Enter your average values and the number of weeks you want to predict</p>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form action="{% url 'authentication:predictions' %}" method="post">
      {% csrf_token %}
      <div class="modal-body">
            <div class="row">
              <input type="text" class="form-control" name="total_calories" placeholder="Total Calories">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_sleep" placeholder="Total Sleep (in minutes)">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_chest" placeholder="Total Amount of sets for chest done above 70% 1RM">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_shoulders" placeholder="Total Amount of sets for shoulders done above 70% 1RM">
            </div>
            <div class="row">
              <input type="text" class="form-control" name="total_triceps" placeholder="Total Amount of sets for triceps done above 70% 1RM">
            </div>
              <div class="row">
                <input type="text" class="form-control" name="total_protein" placeholder="Total Amount of protein consumed (grams)">
              </div>
              <div class="row">
                <input type="text" class="form-control" name="total_carbs" placeholder="Total Amount of carbs consumed (grams)">
              </div>
              <div class="row">
                <input type="text" class="form-control" name="predict_weeks" placeholder="Number of weeks to predict">
              </div>
              <input type="hidden" value="{{ user.id }}" name="user" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn bg-dark text-light">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

  <!-- End Modal Body -->
<body class="d-flex h-100 text-center text-white bg-dark">
    
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
        <div>
            <nav class="nav nav-masthead justify-content-center float-md-start">
                <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="{{ '/' }}">Home</a>
                {% if user.is_authenticated %}
                <a class="nav-link fw-bold py-1 px-0 active" href="{{ 'predictions' }}">Machine Learning Predictions</a>
                {% endif %}
            </nav>
            <div class="float-md-end">
                {% if user.is_authenticated %}
                <span class="mx-2 fw-bold text-light mx-1">{{ user.first_name }} {{ user.last_name }}</span>
                <a href="{% url 'authentication:signout' %}" class="btn btn-secondary fw-bold border-white bg-white">Sign Out</a>
                {% else %}
                <a href="{% url 'authentication:signin' %}" class="btn btn-secondary fw-bold border-white bg-dark text-light mx-1">Sign In</a>
                <a href="{% url 'authentication:signup' %}" class="btn btn-secondary fw-bold border-white bg-white">Sign Up</a>
                {% endif %}
            </div>
        </div>
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" style="text-shadow: none" role="alert">
            <strong>Success! </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        </header>
        
        {% if user.is_authenticated %}
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Bench Strength</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">
                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                    </div>
                    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                    <span data-feather="calendar" class="align-text-bottom"></span>
                    This week
                    </button>
                </div>
            </div>
    
            <canvas class="w-full" id="myChart" width="900" height="380"></canvas>

            <!-- 
                 - Total Calories Consumed that week
                - Total Amount of Sleep that week
                - Total Amount of sets for chest done above 70% 1RM
                - Total Amount of sets for shoulders done above 70% 1RM
                - Total Amount of sets for triceps done above 70% 1RM
                - Total Amount of protein consumed
                - Total Amount of carbohydrates consumed
             -->
            
             <!-- Begin modal button -->
             <button type="button" class="btn btn-secondary fw-bold border-white bg-white mt-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Predict Future Values
            </button>
            <!-- End Modal button -->
            <footer class="mt-auto text-white-50">
                <p>Created by <a href="https://ianboldea.com/" class="text-white">Ian Boldea</a>, &copy; 2022</p>
            </footer>
            <!-- END GRAPH -->
        {% else %}
            <main class="px-3">
            <h1>Let's get you huge.</h1>
            <p class="lead">Use machine learning to get your chest yoked.</p>
            <p class="lead">
                <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
            </p>
            </main>

            <footer class="mt-auto text-white-50">
                <p>Created by <a href="https://ianboldea.com/" class="text-white">Ian Boldea</a>, &copy; 2022</p>
            </footer>
        {% endif %}
    </div>
    <script src="{% static 'authentication/feather.min.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script> 
    <script src="{% static 'authentication/Chart.min.js' %}"></script>
    <script src="{% static 'authentication/date_fns.min.js' %}"></script>
    <script src="{% static 'authentication/chartjs-adapter-date-fns.bundle.min.js' %}"></script>
    <script src="{% static 'authentication/dashboard.js' %}"></script>
</body>
    

authentication/templates/authentication/signin.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'authentication/signinhelper.css' %}">
<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="{% static 'authentication/signin.css' %}">
<body class="text-center bg-dark text-light">
    <main class="form-signin w-100 m-auto" class="text-center">
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Alert! </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        <form action="{% url 'authentication:signin' %}" method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <input name="username" type="text" class="form-control" id="floatingInput" placeholder="Username">
                <label for="floatingInput" class="text-dark">Username</label>
            </div>
            <div class="form-floating">
                <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword" class="text-dark">Password</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
        </form>
    </main>
</body>

authentication/templates/authentication/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'authentication/signinhelper.css' %}">
<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="{% static 'authentication/signin.css' %}">
<body class="text-center bg-dark text-light">
    <main class="form-signin w-100 m-auto" class="text-center">
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Alert! </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        <form action="{% url 'authentication:signup' %}" method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Please sign up</h1>

            <div class="form-floating">
                <input name="username" type="text" class="form-control" id="floatingInput" placeholder="Create a username (alphanumeric)">
                <label for="floatingInput" class="text-dark">Username</label>
            </div>
            <div class="form-floating">
                <input name="firstname" type="text" class="form-control" id="floatingInput" placeholder="Enter your First Name">
                <label for="floatingInput" class="text-dark">First Name</label>
            </div>
            <div class="form-floating">
                <input name="lastname" type="text" class="form-control" id="floatingInput" placeholder="Enter your Last Name">
                <label for="floatingInput" class="text-dark">Last Name</label>
            </div>
            <div class="form-floating">
                <input name="email" type="email" class="form-control" id="floatingInput" placeholder="Enter your email address">
                <label for="floatingInput" class="text-dark">Email Address</label>
            </div>  
            <div class="form-floating">
                <input name="password" type="password" class="form-control" id="floatingInput" placeholder="Enter a password">
                <label for="floatingInput" class="text-dark">Enter a password</label>
            </div>
            <div class="form-floating">
                <input name="confirmpassword" type="password" class="form-control" id="floatingInput" placeholder="Confirm password">
                <label for="floatingInput" class="text-dark">Confirm Password</label>
            </div>
            <br>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign Up</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2022</p>
        </form>
    </main>
</body>
</html>